# Generated by Django 5.2.8 on 2025-11-25 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_alter_walletnonce_purpose'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('approved_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('approved', 'approved'), ('rejected', 'rejected')], max_length=50)),
                ('onchain_loan_id', models.PositiveIntegerField(blank=True, null=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('repaid', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walletprofile')),
            ],
        ),
    ]
