# Generated by Django 5.2.8 on 2025-11-25 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_loan_due_date_loan_repaid_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='asset_name',
            field=models.CharField(default='USDC', max_length=50),
        ),
        migrations.AddField(
            model_name='loan',
            name='total_repay_amount',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True),
        ),
    ]
