# Generated by Django 5.2.8 on 2025-11-25 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_loan_asset_name_loan_total_repay_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='asset_name',
            field=models.CharField(max_length=50),
        ),
    ]
