# Generated by Django 5.2.8 on 2025-11-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_alter_loan_asset_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='loan_duration',
            field=models.IntegerField(default=7),
        ),
    ]
