# Generated by Django 5.2.8 on 2025-12-23 20:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_walletprofile_credit_score'),
        ('dashboard', '0006_alter_loan_loan_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='onchain_loan_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Deposit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('onchain_deposit_id', models.IntegerField(blank=True, null=True)),
                ('asset_name', models.CharField(max_length=50)),
                ('deposit_duration', models.IntegerField()),
                ('deposit_amount', models.DecimalField(decimal_places=6, max_digits=18)),
                ('interest', models.DecimalField(decimal_places=2, max_digits=5)),
                ('withdrawn_amount', models.DecimalField(blank=True, decimal_places=6, max_digits=18, null=True)),
                ('due_date', models.DateTimeField(blank=True, null=True)),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True)),
                ('withdrawn', models.BooleanField(default=False)),
                ('status', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('depositor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.walletprofile')),
            ],
        ),
    ]
