# Generated by Django 5.2.8 on 2025-12-24 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_alter_loan_onchain_loan_id_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deposit',
            name='interest',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
        migrations.AlterField(
            model_name='loan',
            name='interest',
            field=models.DecimalField(decimal_places=6, max_digits=18),
        ),
    ]
