# Generated by Django 5.2.8 on 2025-11-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WalletNonce',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wallet', models.CharField(max_length=42)),
                ('nonce', models.CharField(max_length=16)),
                ('is_used', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='kyc_level_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='kyc_level_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='live_photo',
            field=models.FileField(blank=True, null=True, upload_to='live_photo/'),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
