# Generated by Django 5.2.8 on 2025-11-23 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_walletnonce_walletprofile_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletprofile',
            name='skipped',
            field=models.BooleanField(default=False),
        ),
    ]
