# Generated by Django 5.2.8 on 2025-11-23 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_walletprofile_skipped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
