# Generated by Django 5.2.8 on 2025-11-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_walletprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='walletprofile',
            name='last_name',
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='dob',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
