# Generated by Django 5.2.8 on 2025-11-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_walletprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletprofile',
            name='docType',
            field=models.CharField(default='Hello', max_length=100),
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='kyc_level_3',
            field=models.BooleanField(default=False),
        ),
    ]
