# Generated by Django 5.2.8 on 2025-11-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_walletprofile_doctype_walletprofile_kyc_level_3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletprofile',
            name='docType',
            field=models.CharField(max_length=100),
        ),
    ]
