# Generated by Django 5.2.8 on 2025-11-23 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_walletprofile_doctype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletprofile',
            name='live_photo',
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='selfie',
            field=models.FileField(blank=True, null=True, upload_to='selfie/'),
        ),
    ]
