# Generated by Django 5.2.8 on 2025-11-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_walletprofile_live_photo_walletprofile_selfie'),
    ]

    operations = [
        migrations.RenameField(
            model_name='walletprofile',
            old_name='id_document',
            new_name='id_document_back',
        ),
        migrations.AddField(
            model_name='walletprofile',
            name='id_document_front',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
