# Generated by Django 5.2.8 on 2025-11-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_rename_id_document_walletprofile_id_document_back_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletnonce',
            name='purpose',
            field=models.CharField(choices=[('auth', 'Wallet Authentication'), ('kyc_consent', 'KYC Consent')], default='auth', max_length=20),
        ),
    ]
