# Generated by Django 5.2.8 on 2025-11-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_walletnonce_purpose'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletnonce',
            name='purpose',
            field=models.CharField(choices=[('auth', 'Wallet Authentication'), ('kyc_consent', 'KYC Consent')], max_length=20),
        ),
    ]
