# Generated by Django 5.2.8 on 2025-11-26 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_alter_walletnonce_purpose'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletprofile',
            name='credit_score',
            field=models.FloatField(default=0.5),
        ),
    ]
