# Generated by Django 5.2.8 on 2025-12-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_walletprofile_credit_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletnonce',
            name='nonce',
            field=models.CharField(max_length=128),
        ),
    ]
